name: 'Set property string value in a json file'
description: 'Set property string value in a json file (ex. appsettings.json)'
author: 'Benjamin Day Consulting, Inc.'
inputs:
  pathToSettingsFile:
    required: true
    description: 'Path to the json file to edit (appsettings.json)'
    default: 'appsettings.json'
  keyname1:
    required: true
    description: 'The name of the first level property in the json hierarchy.'
  keyname2:
    required: false
    description: '[optional] The name of the second level property in the json hierarchy.'
    default: null
  keyname3:
    required: false
    description: '[optional] The name of the third level property in the json hierarchy.'
    default: null
  valueToSet:
    required: true
    description: 'value for the connection string'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'settings'
  color: 'blue'
